language: node_js
node_js:
  - "lts/argon"
  - "lts/boron"
  - "lts/carbon"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn build
after_script:
  - yarn test:coverage && nyc report --reporter=text-lcov | coveralls
notifications:
  email:
    on_success: change
    on_failure: always
