name: Build Status
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci:
    name: Test the build

    runs-on: ubuntu-latest

    env:
      CI: true

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        yarn --frozen-lockfile
        yarn lint
        yarn test:coverage
        yarn compile
    - name: Coveralls
      if: matrix.node-version == 12.x
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
